name: Publish TS Client to npmjs

on:
  workflow_dispatch:
  push:
    tags:
      - 'client-ts-v*'

jobs:
  publish-npmjs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Build client
        run: |
          npm -C clients/typescript ci
          npm -C clients/typescript run gen
          if git diff --name-only HEAD^ HEAD | grep -q 'openapi.yaml'; then
            node -e "const fs=require('fs');const p='./clients/typescript/package.json';const j=JSON.parse(fs.readFileSync(p));const [maj,min,patch]=j.version.split('.').map(Number);j.version=[maj,min+1,0].join('.');fs.writeFileSync(p,JSON.stringify(j,null,2));"
          fi
          npm -C clients/typescript run build
      - name: Publish to npmjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          PKG_VERSION=$(node -e "console.log(require('./clients/typescript/package.json').version)")
          echo "Publishing version $PKG_VERSION"
          npm -C clients/typescript publish --access public --registry=https://registry.npmjs.org